-- FilaFacil Acessivel - estrutura de autenticacao por perfil
-- Execute este script no SQL Editor do Supabase.

create table if not exists public.app_users (
  id bigint generated by default as identity primary key,
  auth_user_id uuid not null unique references auth.users(id) on delete cascade,
  username text not null unique,
  role text not null check (role in ('attendant', 'doctor', 'admin')),
  is_active boolean not null default true,
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now())
);

create unique index if not exists app_users_username_key on public.app_users (username);
create index if not exists app_users_role_idx on public.app_users (role);
create index if not exists app_users_is_active_idx on public.app_users (is_active);

create or replace function public.set_app_users_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = timezone('utc', now());
  return new;
end;
$$;

drop trigger if exists trg_app_users_updated_at on public.app_users;
create trigger trg_app_users_updated_at
before update on public.app_users
for each row execute function public.set_app_users_updated_at();

alter table public.app_users enable row level security;

drop policy if exists "app_users_read_own_profile" on public.app_users;
create policy "app_users_read_own_profile"
on public.app_users
for select
to authenticated
using (auth.uid() = auth_user_id);
